name: Rust

on:
  push:
    tags: "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Output rust version for educational purposes
      run: rustup --version
    - name: Run tests
      run: cargo test --verbose
    - uses: ryohidaka/action-cargo-publish@v0.1.0
      with:
        token: ${{ secrets.CRATES_IO_TOKEN }}
        dry-run: true
